//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DNAViewReportFinalDRB345Assignments
    {
        public string sampleID { get; set; }
        public int LocusID { get; set; }
        public Nullable<int> Locus { get; set; }
        public string locusName { get; set; }
        public string Batch { get; set; }
        public string ag1 { get; set; }
        public string ag2 { get; set; }
        public int Yloc { get; set; }
        public string MatchType { get; set; }
    }
}
