//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DNAViewReportHeader
    {
        public string patientName { get; set; }
        public string sampleID { get; set; }
        public Nullable<System.DateTime> patientDOB { get; set; }
        public Nullable<System.DateTime> drawDt { get; set; }
        public string donorNumber { get; set; }
        public string donorCenterNumber { get; set; }
        public string accession { get; set; }
        public Nullable<System.DateTime> createDt { get; set; }
        public string sessionID { get; set; }
    }
}
