//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class LMXReportDataVBAFView
    {
        public string sessionID { get; set; }
        public string Batch_Name { get; set; }
        public string wellLocation { get; set; }
        public string Well_Location { get; set; }
        public string sampleID { get; set; }
        public string Sample_ID { get; set; }
        public string patientName { get; set; }
        public string Patient_Name { get; set; }
        public Nullable<System.DateTime> drawDt { get; set; }
        public string AssayName { get; set; }
        public string Assay_Name { get; set; }
        public string LotID { get; set; }
        public string Lot_ID { get; set; }
        public System.DateTime ExpirationDate { get; set; }
        public Nullable<decimal> CI_01_MFI { get; set; }
        public Nullable<decimal> CI_01_hiBGAdjust1 { get; set; }
        public Nullable<decimal> CI_01_hiBGAdjust2 { get; set; }
        public Nullable<decimal> CI_01_hiBGAdjust3 { get; set; }
        public Nullable<int> CI_01_HIScore { get; set; }
        public Nullable<decimal> CI_02_MFI { get; set; }
        public Nullable<decimal> CI_02_hiBGAdjust1 { get; set; }
        public Nullable<decimal> CI_02_hiBGAdjust2 { get; set; }
        public Nullable<decimal> CI_02_hiBGAdjust3 { get; set; }
        public Nullable<int> CI_02_HIScore { get; set; }
        public Nullable<decimal> CI_03_MFI { get; set; }
        public Nullable<decimal> CI_03_hiBGAdjust1 { get; set; }
        public Nullable<decimal> CI_03_hiBGAdjust2 { get; set; }
        public Nullable<decimal> CI_03_hiBGAdjust3 { get; set; }
        public Nullable<int> CI_03_HISCORE { get; set; }
        public Nullable<decimal> CI_04_MFI { get; set; }
        public Nullable<decimal> CI_04_hiBGAdjust1 { get; set; }
        public Nullable<decimal> CI_04_hiBGAdjust2 { get; set; }
        public Nullable<decimal> CI_04_hiBGAdjust3 { get; set; }
        public Nullable<int> CI_04_HISCORE { get; set; }
        public Nullable<decimal> CI_05_MFI { get; set; }
        public Nullable<decimal> CI_05_hiBGAdjust1 { get; set; }
        public Nullable<decimal> CI_05_hiBGAdjust2 { get; set; }
        public Nullable<decimal> CI_05_hiBGAdjust3 { get; set; }
        public Nullable<int> CI_05_HISCORE { get; set; }
        public Nullable<decimal> CI_06_MFI { get; set; }
        public Nullable<decimal> CI_06_hiBGAdjust1 { get; set; }
        public Nullable<decimal> CI_06_hiBGAdjust2 { get; set; }
        public Nullable<decimal> CI_06_hiBGAdjust3 { get; set; }
        public Nullable<int> CI_06_HISCORE { get; set; }
        public Nullable<decimal> CI_07_MFI { get; set; }
        public Nullable<decimal> CI_07_hiBGAdjust1 { get; set; }
        public Nullable<decimal> CI_07_hiBGAdjust2 { get; set; }
        public Nullable<decimal> CI_07_hiBGAdjust3 { get; set; }
        public Nullable<int> CI_07_HISCORE { get; set; }
        public string ClassIResults { get; set; }
        public string ClassIOverride { get; set; }
        public Nullable<decimal> CII_01_MFI { get; set; }
        public Nullable<decimal> CII_01_hiBGAdjust1 { get; set; }
        public Nullable<decimal> CII_01_hiBGAdjust2 { get; set; }
        public Nullable<decimal> CII_01_hiBGAdjust3 { get; set; }
        public Nullable<int> CII_01_HISCORE { get; set; }
        public Nullable<decimal> CII_02_MFI { get; set; }
        public Nullable<decimal> CII_02_hiBGAdjust1 { get; set; }
        public Nullable<decimal> CII_02_hiBGAdjust2 { get; set; }
        public Nullable<decimal> CII_02_hiBGAdjust3 { get; set; }
        public Nullable<int> CII_02_HISCORE { get; set; }
        public Nullable<decimal> CII_03_MFI { get; set; }
        public Nullable<decimal> CII_03_hiBGAdjust1 { get; set; }
        public Nullable<decimal> CII_03_hiBGAdjust2 { get; set; }
        public Nullable<decimal> CII_03_hiBGAdjust3 { get; set; }
        public Nullable<int> CII_03_HISCORE { get; set; }
        public Nullable<decimal> CII_04_MFI { get; set; }
        public Nullable<decimal> CII_04_hiBGAdjust1 { get; set; }
        public Nullable<decimal> CII_04_hiBGAdjust2 { get; set; }
        public Nullable<decimal> CII_04_hiBGAdjust3 { get; set; }
        public Nullable<int> CII_04_HISCORE { get; set; }
        public Nullable<decimal> CII_05_MFI { get; set; }
        public Nullable<decimal> CII_05_hiBGAdjust1 { get; set; }
        public Nullable<decimal> CII_05_hiBGAdjust2 { get; set; }
        public Nullable<decimal> CII_05_hiBGAdjust3 { get; set; }
        public Nullable<int> CII_05_HISCORE { get; set; }
        public string ClassIIResults { get; set; }
        public string ClassIIOverride { get; set; }
        public Nullable<decimal> CON1 { get; set; }
        public Nullable<decimal> CON2 { get; set; }
        public Nullable<decimal> CON3 { get; set; }
        public Nullable<decimal> C77 { get; set; }
        public Nullable<System.DateTime> runDate { get; set; }
        public string comments { get; set; }
        public int ctrlSampleFailed { get; set; }
        public Nullable<int> CI_01_BeadCount { get; set; }
        public Nullable<int> CI_02_BeadCount { get; set; }
        public Nullable<int> CI_03_BeadCount { get; set; }
        public Nullable<int> CI_04_BeadCount { get; set; }
        public Nullable<int> CI_05_BeadCount { get; set; }
        public Nullable<int> CI_06_BeadCount { get; set; }
        public Nullable<int> CI_07_BeadCount { get; set; }
        public Nullable<int> CII_01_BeadCount { get; set; }
        public Nullable<int> CII_02_BeadCount { get; set; }
        public Nullable<int> CII_03_BeadCount { get; set; }
        public Nullable<int> CII_04_BeadCount { get; set; }
        public Nullable<int> CII_05_BeadCount { get; set; }
        public int useVBAF { get; set; }
        public bool useMFICutoff { get; set; }
        public Nullable<decimal> MFICutoffValue { get; set; }
        public string Update_Date { get; set; }
        public Nullable<System.DateTime> updatedt { get; set; }
        public string Expiration_Date { get; set; }
        public string ReportDate { get; set; }
        public string Draw_Date { get; set; }
        public string Test_Date { get; set; }
        public Nullable<System.DateTime> testDt { get; set; }
        public string Run_Date { get; set; }
        public int AntibodyID { get; set; }
        public string Accession { get; set; }
        public Nullable<System.DateTime> patientDOB { get; set; }
        public string Patient_DOB { get; set; }
        public string donorCenterNumber { get; set; }
        public string Donor_Center_Number { get; set; }
        public string userDefinedName { get; set; }
        public string donorNumber { get; set; }
        public string Donor_Number { get; set; }
        public int Control_Sample_Failed { get; set; }
        public string Reviewer { get; set; }
        public string Completed_By { get; set; }
        public Nullable<System.DateTime> Completed_Date { get; set; }
        public string Approved_By { get; set; }
        public Nullable<System.DateTime> Approved_Date { get; set; }
    }
}
