//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class matchitEntities : DbContext
    {
        public matchitEntities()
            : base("name=matchitEntities")
        {
        }
        public matchitEntities(string connString)
                : base(connString)
        {
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbAntibodyLot> tbAntibodyLot { get; set; }
        public virtual DbSet<tbAntibodyMethod> tbAntibodyMethod { get; set; }
        public virtual DbSet<tbAntigens> tbAntigens { get; set; }
        public virtual DbSet<tbBatch> tbBatch { get; set; }
        public virtual DbSet<tbBeadHits> tbBeadHits { get; set; }
        public virtual DbSet<tbDNAAllele> tbDNAAllele { get; set; }
        public virtual DbSet<tbDNAData> tbDNAData { get; set; }
        public virtual DbSet<tbDNAFinalAssignment> tbDNAFinalAssignment { get; set; }
        public virtual DbSet<tbDNALot> tbDNALot { get; set; }
        public virtual DbSet<tbDNAMethod> tbDNAMethod { get; set; }
        public virtual DbSet<tbDNASuggestedAssignments> tbDNASuggestedAssignments { get; set; }
        public virtual DbSet<tbAlleleProbeVals> tbAlleleProbeVals { get; set; }
        public virtual DbSet<tbAntibodyData> tbAntibodyData { get; set; }
        public virtual DbSet<tbAntibodyExpSet> tbAntibodyExpSet { get; set; }
        public virtual DbSet<tbAntibodyStats> tbAntibodyStats { get; set; }
        public virtual DbSet<tbDBVer> tbDBVer { get; set; }
        public virtual DbSet<tbDNAExpSet> tbDNAExpSet { get; set; }
        public virtual DbSet<DNAFinalAssignmentView> DNAFinalAssignmentView { get; set; }
        public virtual DbSet<SingleAntigenV2ExportView> SingleAntigenV2ExportView { get; set; }
        public virtual DbSet<DNAViewReportHeader> DNAViewReportHeader { get; set; }
        public virtual DbSet<DNAViewReportFinalAssignments> DNAViewReportFinalAssignments { get; set; }
        public virtual DbSet<DNAViewReportFinalDRB345Assignments> DNAViewReportFinalDRB345Assignments { get; set; }
        public virtual DbSet<tbAntibodyResults> tbAntibodyResults { get; set; }
        public virtual DbSet<LMXReportDataVBAFView> LMXReportDataVBAFView { get; set; }
        public virtual DbSet<LMXReportDataView> LMXReportDataView { get; set; }
        public virtual DbSet<SingleAntigenOncCONExportView> SingleAntigenOncCONExportView { get; set; }
    }
}
