//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SingleAntigenV2ExportView
    {
        public string Batch_Name { get; set; }
        public string Sample_ID { get; set; }
        public string Patient_Name { get; set; }
        public string HLA_Type { get; set; }
        public string Draw_Date { get; set; }
        public string Accession { get; set; }
        public string Donor_Center_Number { get; set; }
        public string Patient_DOB { get; set; }
        public string User_Defined_Name { get; set; }
        public string Donor_Number { get; set; }
        public string Antigen_ID { get; set; }
        public string Allele { get; set; }
        public string Assignment { get; set; }
        public Nullable<decimal> Raw_Value { get; set; }
        public string Completed_By { get; set; }
        public string Approved_By { get; set; }
        public string Approved_Date { get; set; }
        public string Completed_Date { get; set; }
        public string sessionID { get; set; }
        public string Assay_Name { get; set; }
        public string Comments { get; set; }
        public string Run_Date { get; set; }
        public Nullable<decimal> PRA { get; set; }
        public string Lot_ID { get; set; }
        public string Assignment_List { get; set; }
        public string Well_Location { get; set; }
        public string Expiration_Date { get; set; }
        public string Serology { get; set; }
        public Nullable<decimal> BG_Adjusted { get; set; }
        public Nullable<decimal> MFI_LRA { get; set; }
        public Nullable<decimal> AD_MFI { get; set; }
        public Nullable<decimal> AD_BG_Adjusted { get; set; }
        public Nullable<decimal> Cutoff { get; set; }
    }
}
