//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SingleAntigenOncCONExportView
    {
        public string Batch_Name { get; set; }
        public string sampleID { get; set; }
        public string patientName { get; set; }
        public string hlaType { get; set; }
        public string drawDt { get; set; }
        public string accession { get; set; }
        public string donorCenterNumber { get; set; }
        public string patientDOB { get; set; }
        public string userDefinedName { get; set; }
        public string donorNumber { get; set; }
        public string bead { get; set; }
        public string allele { get; set; }
        public string assignment { get; set; }
        public Nullable<decimal> rawValue { get; set; }
        public string completedBy { get; set; }
        public string approvedBy { get; set; }
        public string ApprovedDt { get; set; }
        public string CompletedDt { get; set; }
        public string sessionID { get; set; }
        public Nullable<decimal> BCM { get; set; }
        public Nullable<decimal> BCR { get; set; }
        public Nullable<decimal> AD_BCR { get; set; }
        public Nullable<decimal> CON1 { get; set; }
        public Nullable<int> CON2 { get; set; }
        public Nullable<int> CON3 { get; set; }
        public Nullable<decimal> Probe_77 { get; set; }
        public string AssayName { get; set; }
        public string comments { get; set; }
        public string runDate { get; set; }
        public Nullable<decimal> pra { get; set; }
        public string lotID { get; set; }
        public string Assignment_List { get; set; }
        public string wellLocation { get; set; }
        public string ExpirationDate { get; set; }
        public int locusID { get; set; }
        public string Serology { get; set; }
    }
}
