//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbAlleleProbeVals
    {
        public int logicId { get; set; }
        public string allele { get; set; }
        public int alleleLogicalPosition { get; set; }
        public string probeName { get; set; }
        public int probeLogicalPosition { get; set; }
        public int positiveFlag { get; set; }
    }
}
