//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbAntigens
    {
        public int AntigenID { get; set; }
        public string AntigenName { get; set; }
        public Nullable<int> AntigenClass { get; set; }
        public string AntigenColor { get; set; }
        public string Serology { get; set; }
        public string ExcludedAntigenOptions { get; set; }
        public Nullable<int> AntigenSortOrder { get; set; }
        public Nullable<int> SerologySortOrder { get; set; }
    }
}
