//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbAntibodyData
    {
        public int AntibodyID { get; set; }
        public string bead { get; set; }
        public string lotID { get; set; }
        public Nullable<decimal> rawValue { get; set; }
        public Nullable<decimal> adjust1 { get; set; }
        public Nullable<decimal> adjust2 { get; set; }
        public Nullable<decimal> adjust3 { get; set; }
        public Nullable<decimal> adjustN { get; set; }
        public Nullable<int> score { get; set; }
        public string assignment { get; set; }
        public Nullable<System.DateTime> testDt { get; set; }
        public Nullable<decimal> hiBGAdjust1 { get; set; }
        public Nullable<decimal> hiBGAdjust2 { get; set; }
        public Nullable<decimal> hiBGAdjust3 { get; set; }
        public Nullable<int> hiBGScore { get; set; }
        public string hiBGAssignment { get; set; }
        public Nullable<decimal> weakPct { get; set; }
        public Nullable<int> overRide { get; set; }
        public Nullable<int> beadCount { get; set; }
        public string epletAssignment { get; set; }
    
        public virtual tbAntibodyMethod tbAntibodyMethod { get; set; }
    }
}
