//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbAntibodyMethod
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbAntibodyMethod()
        {
            this.tbAntibodyData = new HashSet<tbAntibodyData>();
            this.tbAntibodyStats = new HashSet<tbAntibodyStats>();
            this.tbAntibodyResults = new HashSet<tbAntibodyResults>();
        }
    
        public int AntibodyID { get; set; }
        public string lotID { get; set; }
        public string sessionID { get; set; }
        public string sampleID { get; set; }
        public Nullable<int> logicID { get; set; }
        public string wellLocation { get; set; }
        public Nullable<decimal> raw { get; set; }
        public Nullable<decimal> rVal { get; set; }
        public Nullable<int> pctPositive { get; set; }
        public Nullable<int> assignCutoff { get; set; }
        public Nullable<decimal> assignAdjust1 { get; set; }
        public Nullable<decimal> assignAdjust2 { get; set; }
        public Nullable<decimal> assignAdjust3 { get; set; }
        public Nullable<int> tail { get; set; }
        public Nullable<System.DateTime> runDate { get; set; }
        public string comments { get; set; }
        public Nullable<int> includeweak { get; set; }
        public Nullable<int> reviewer { get; set; }
        public Nullable<System.DateTime> reviewerDt { get; set; }
        public Nullable<System.DateTime> createdt { get; set; }
        public Nullable<System.DateTime> updatedt { get; set; }
        public Nullable<int> updateby { get; set; }
        public Nullable<int> manualAssignFlg { get; set; }
        public int ctrlSampleFailed { get; set; }
        public int lockedFlg { get; set; }
        public int approved { get; set; }
        public int useVBAF { get; set; }
        public Nullable<bool> negativeCtrl { get; set; }
        public Nullable<decimal> pra { get; set; }
        public Nullable<decimal> virtualPra { get; set; }
        public int CalcUsed { get; set; }
        public int completed { get; set; }
        public Nullable<int> completedBy { get; set; }
        public Nullable<int> approvedBy { get; set; }
        public string maskedAntigens { get; set; }
        public Nullable<System.DateTime> ApprovedDt { get; set; }
        public Nullable<System.DateTime> CompletedDt { get; set; }
        public bool useMFICutoff { get; set; }
        public Nullable<decimal> MFICutoffValue { get; set; }
        public Nullable<int> ID4DigitLogicID { get; set; }
        public Nullable<decimal> adjAltCalc1 { get; set; }
        public Nullable<decimal> adjAltCalc2 { get; set; }
        public Nullable<int> TailLogicID { get; set; }
        public Nullable<int> excludeweak { get; set; }
        public Nullable<int> Version { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbAntibodyData> tbAntibodyData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbAntibodyStats> tbAntibodyStats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbAntibodyResults> tbAntibodyResults { get; set; }
    }
}
