//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbBatch
    {
        public int batchID { get; set; }
        public Nullable<int> locusID { get; set; }
        public string sessionID { get; set; }
        public string lotID { get; set; }
        public string logicName { get; set; }
        public string assayName { get; set; }
        public string submittedBy { get; set; }
        public string batchDesc { get; set; }
        public string batchName { get; set; }
        public string batchStatus { get; set; }
        public string bServer { get; set; }
        public string bDatabase { get; set; }
        public Nullable<int> numOfSamples { get; set; }
        public Nullable<System.DateTime> createDt { get; set; }
        public Nullable<System.DateTime> lastSubmitDt { get; set; }
        public Nullable<int> traliBatchFlag { get; set; }
        public string batchOperator { get; set; }
        public string startPos { get; set; }
        public int ReviewedCount { get; set; }
    }
}
