//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbBeadHits
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbBeadHits()
        {
            this.tbDNAAllele = new HashSet<tbDNAAllele>();
        }
    
        public int ID { get; set; }
        public int LocusID { get; set; }
        public string Pattern { get; set; }
        public int DNALotID { get; set; }
        public string Alleles { get; set; }
    
        public virtual tbDNALot tbDNALot { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbDNAAllele> tbDNAAllele { get; set; }
    }
}
