//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbDNAExpSet
    {
        public int DNALotID { get; set; }
        public string Bead { get; set; }
        public Nullable<int> sortOrder { get; set; }
        public Nullable<decimal> highNegative { get; set; }
        public Nullable<decimal> lowPositive { get; set; }
        public Nullable<int> consensus { get; set; }
        public Nullable<decimal> threshold { get; set; }
        public Nullable<decimal> controlValue { get; set; }
        public string specificity { get; set; }
        public Nullable<System.DateTime> createdt { get; set; }
        public Nullable<System.DateTime> updatedt { get; set; }
        public string updateby { get; set; }
    
        public virtual tbDNALot tbDNALot { get; set; }
    }
}
