//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbDNASuggestedAssignments
    {
        public int DNAID { get; set; }
        public int HLAIDAG1 { get; set; }
        public int HLAIDAG2 { get; set; }
        public int MatchType { get; set; }
        public string WhatIfProbe { get; set; }
        public bool Final { get; set; }
        public bool isNullCombine { get; set; }
        public bool isHiResCombine { get; set; }
        public System.DateTime createDt { get; set; }
        public Nullable<System.DateTime> updateDt { get; set; }
        public Nullable<int> updateBy { get; set; }
    
        public virtual tbDNAAllele tbDNAAllele { get; set; }
        public virtual tbDNAAllele tbDNAAllele1 { get; set; }
        public virtual tbDNAMethod tbDNAMethod { get; set; }
    }
}
