//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbDNAData
    {
        public int DNAID { get; set; }
        public string probeName { get; set; }
        public Nullable<decimal> adjValue { get; set; }
        public Nullable<decimal> rawMFI { get; set; }
        public Nullable<int> result { get; set; }
        public Nullable<int> manualOverrideFlg { get; set; }
        public Nullable<decimal> cutoffValue { get; set; }
        public Nullable<decimal> originalCutoffValue { get; set; }
        public Nullable<System.DateTime> updatedt { get; set; }
        public string updateby { get; set; }
        public Nullable<int> scoredAndTyped { get; set; }
        public int id { get; set; }
        public Nullable<int> beadCount { get; set; }
    
        public virtual tbDNAMethod tbDNAMethod { get; set; }
    }
}
