//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbDNAFinalAssignment
    {
        public string sampleID { get; set; }
        public string ag1 { get; set; }
        public string ag2 { get; set; }
        public Nullable<int> DNALotID { get; set; }
        public Nullable<int> DNAID { get; set; }
        public int LocusID { get; set; }
        public string AlleleTyping { get; set; }
        public string AlleleDBVer { get; set; }
    
        public virtual tbDNALot tbDNALot { get; set; }
    }
}
