//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbDNAMethod
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbDNAMethod()
        {
            this.tbDNAData = new HashSet<tbDNAData>();
            this.tbDNASuggestedAssignments = new HashSet<tbDNASuggestedAssignments>();
        }
    
        public int DNAID { get; set; }
        public int DNALotID { get; set; }
        public string sessionID { get; set; }
        public string sampleID { get; set; }
        public int samplePosition { get; set; }
        public Nullable<bool> repeatRequired { get; set; }
        public Nullable<bool> reportable { get; set; }
        public string hiResRequired { get; set; }
        public Nullable<System.DateTime> createDt { get; set; }
        public string updateby { get; set; }
        public Nullable<System.DateTime> updateDt { get; set; }
        public Nullable<bool> isDRBHomoz { get; set; }
        public Nullable<bool> confirmed { get; set; }
        public Nullable<int> completedBy { get; set; }
        public Nullable<System.DateTime> completedDt { get; set; }
        public Nullable<int> approvedBy { get; set; }
        public Nullable<System.DateTime> approvedDt { get; set; }
        public Nullable<int> plistNo { get; set; }
        public Nullable<System.DateTime> rundate { get; set; }
        public Nullable<System.DateTime> reportDate { get; set; }
        public string WellLocation { get; set; }
        public Nullable<int> SampleStatus { get; set; }
        public Nullable<bool> Exclude { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbDNAData> tbDNAData { get; set; }
        public virtual tbDNALot tbDNALot { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbDNASuggestedAssignments> tbDNASuggestedAssignments { get; set; }
    }
}
