//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbDNALot
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbDNALot()
        {
            this.tbBeadHits = new HashSet<tbBeadHits>();
            this.tbDNAFinalAssignment = new HashSet<tbDNAFinalAssignment>();
            this.tbDNAExpSet = new HashSet<tbDNAExpSet>();
            this.tbDNAMethod = new HashSet<tbDNAMethod>();
        }
    
        public int ID { get; set; }
        public string LotID { get; set; }
        public Nullable<int> locusID { get; set; }
        public System.DateTime ExpirationDate { get; set; }
        public string AssayName { get; set; }
        public string AssayVersion { get; set; }
        public string alleleDBVersion { get; set; }
        public bool Available { get; set; }
        public Nullable<int> BeadCount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbBeadHits> tbBeadHits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbDNAFinalAssignment> tbDNAFinalAssignment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbDNAExpSet> tbDNAExpSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbDNAMethod> tbDNAMethod { get; set; }
    }
}
